<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Absences.Domain\Absences.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
    <ProjectReference Include="..\..\Employees\Employees.Contracts\Employees.Contracts.csproj" />
  </ItemGroup>
</Project>
